### ISSUE TITLE
23,437,586,000 BTT Missing in Bridge Transaction

### ISSUE THREAD

**Issue by prabudbz** [bttcprotocol/bttc#13]
I have been using BTT bridge since its launch for transferring BTT from BTTC network to ERC20 OR BSC.
I tried to transfer 23,437,586,000 BTT from BTTC to the BSC network.
First I swapped my 23,437,586,000 BTT using the swap to convert BTT to BTT_b and then I go to wallet and withdraw BTT_b to BTT BSC network but I can't find the transaction anywhere on the records page and I can't withdraw it to BSC network.

Both the swap and withdraw transaction hashes are below

TRX address - TFfUEhJ339qPbChcjjyj9hksEFZo7pEbfc
BTTC chain address - 0xbceb9733137f6584aee74939de8dd082da3fd94a

Transaction hash 1 - 0xf30f43dc3751423a6a5db2a47540a87539aff5a5b7bfe0210ab06d7169e87719 (BTT to BTT_b)
Transaction hash 2 - 0x7be8656702b32e27f420d95477b1b8b720320423ad533390274b6f828719d2aa (BTT_b to BTT (bsc))

Please help to resolve this issue and get my 23,437,586,000 BTT back.

Please find below the screenshots for the missing transaction on the records page for withdrawal to the BSC network.
The transaction with the above hash is missing while the previous transaction of 25,641,512,000 BTT_b is showing and also the next transaction of 102 BTT_b is also showing.

<img width="1439" alt="Screenshot 2022-02-19 at 7 33 53 AM" src="https://user-images.githubusercontent.com/7588200/154784612-d2706ef4-b87c-49aa-ab1e-3575d1e0b615.png">
<img width="1433" alt="Screenshot 2022-02-19 at 7 34 10 AM" src="https://user-images.githubusercontent.com/7588200/154784618-b2622a85-636d-425f-b4b9-94a30e965a8b.png">
<img width="1426" alt="Screenshot 2022-02-19 at 7 34 41 AM" src="https://user-images.githubusercontent.com/7588200/154784624-544c32d5-0e4a-4857-9b75-0c05689017e8.png">
<img width="1439" alt="Screenshot 2022-02-19 at 7 34 47 AM" src="https://user-images.githubusercontent.com/7588200/154784625-d18a03c4-a53e-4394-9461-4225fb34a70b.png">
<img width="1435" alt="Screenshot 2022-02-19 at 7 35 00 AM" src="https://user-images.githubusercontent.com/7588200/154784627-0918e107-28b0-4117-a32c-8666be51fe99.png">

**Comment by qewetfty** [comment]
We have reprocessed the transaction 0x7be8656702b32e27f420d95477b1b8b720320423ad533390274b6f828719d2aa and you can try to withdraw your BTT_b.

**Comment by prabudbz** [comment]
Thank you so much, it was solved and I had withdrawn it.
