### ISSUE TITLE
RE: BTT fund sent to incorrect address

### ISSUE THREAD

**Issue by KELVINKZQ** [bttcprotocol/bttc#14]
Hi, i need help, BTT coin sent to the incorrect address. How do i recover the coin?
Many thanks.

TXID: 449a2b29a9e38ca382898989b996e609415ae3785ab572381e7c3c87c81800bd

**Comment by okwapa210** [comment]
> Hi, i need help, BTT coin sent to the incorrect address. How do i recover the coin? Many thanks.
> 
> TXID: 449a2b29a9e38ca382898989b996e609415ae3785ab572381e7c3c87c81800bd

You transfer BTT to the BTT contract address?
No way to recover the coin, If a smart contract does not have a withdrawal API, no one can get your coin back. Almost all TRC20 contracts, including BTT contract, does not support such operations.

**Comment by KELVINKZQ** [comment]
yes, i transferred into the BTT contract address.
i know right, i could have verified it before i send over.
