### ISSUE TITLE
Btt_e record transfer bug

### ISSUE THREAD

**Issue by Selambeners** [bttcprotocol/bttc#17]
Hash.
0xf823c8b910a19e8af5c88764810d2aba4c52641f4fa56670434b8308d90cc3e3

My cross chain btt-e transaction record cannot be displayed.

![IMG_20220225_004656](https://user-images.githubusercontent.com/100384079/155613210-04b64d5a-3990-460d-a32a-52736f16ecf4.jpg)

Wallet: 0x3bed80c0974c4ef82b5286d696b480af761c019e

**Comment by prabudbz** [comment]
Same issue, I tried to transfer from BTT_e to BTT (Ethereum network), even after the few checkpoints have been completed the transaction is not showing in all records for withdrawal.

Wallet address: 0xbceb9733137f6584aee74939de8dd082da3fd94a
Transaction Hash: 0xdb5108d2ea59d66a64cfa9358c7445fb66997e056405a4a546e234cd82a34d83

Kindly please help to solve the issue.
<img width="1319" alt="Screenshot 2022-02-25 at 7 33 35 AM" src="https://user-images.githubusercontent.com/7588200/155639852-d85507ab-487b-41c7-8d65-6f618940c3c9.png">
<img width="1345" alt="Screenshot 2022-02-25 at 7 33 50 AM" src="https://user-images.githubusercontent.com/7588200/155639869-3a019617-97a3-44e7-905e-6885a5dabda5.png">

**Comment by prabudbz** [comment]
> Same issue, I tried to transfer from BTT_e to BTT (Ethereum network), even after the few checkpoints have been completed the transaction is not showing in all records for withdrawal.
> 
> Wallet address: 0xbceb9733137f6584aee74939de8dd082da3fd94a Transaction Hash: 0xdb5108d2ea59d66a64cfa9358c7445fb66997e056405a4a546e234cd82a34d83
> 
> Kindly please help to solve the issue. <img alt="Screenshot 2022-02-25 at 7 33 35 AM" width="1319" src="https://user-images.githubusercontent.com/7588200/155639852-d85507ab-487b-41c7-8d65-6f618940c3c9.png"> <img alt="Screenshot 2022-02-25 at 7 33 50 AM" width="1345" src="https://user-images.githubusercontent.com/7588200/155639869-3a019617-97a3-44e7-905e-6885a5dabda5.png">

It's been solved now, thank you.

**Comment by zhang0125** [comment]
> Hash. 0xf823c8b910a19e8af5c88764810d2aba4c52641f4fa56670434b8308d90cc3e3
> 
> My cross chain btt-e transaction record cannot be displayed.
> 
> ![IMG_20220225_004656](https://user-images.githubusercontent.com/100384079/155613210-04b64d5a-3990-460d-a32a-52736f16ecf4.jpg)
> 
> Wallet: 0x3bed80c0974c4ef82b5286d696b480af761c019e

I observed that this cross chain btt-e transaction has been completed. There may be some delay in the cross chain transaction because the transaction sent on Ether may be put into the pending queue.
