### ISSUE TITLE
Test network - the bttc cannot be synchronized when deploying the validator node

### ISSUE THREAD

**Issue by cppfuns** [bttcprotocol/bttc#30]
I refer to the following documents to deploy a validator node of the test network

https://doc.bt.io/docs/validator/build-validator-node

When configuring the Sentry Nodes, Delivery and bttc are already configured. However, after the bttc node is started, other peers cannot be added. The following errors appear in the log

![image](https://user-images.githubusercontent.com/7980920/199633002-408b60f9-04a9-4630-9d7b-951262768be3.png)

Is there a problem with my configuration?

----Additional information----

Execute query command `curl localhost:26657/status`
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "1dc05d2a65b6c322ebf231375516c9d6b5079920",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "delivery-1029",
      "version": "0.32.7",
      "channels": "4020212223303800",
      "moniker": "xxxx-test-5",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://127.0.0.1:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "67601D512F749F0DB5DEAA63543AE53C921155A8922CDE38E0730E725C3B2710",
      "latest_app_hash": "1E6F134FF6070D15432FACCCB3E2985F4F0F6512078F9D13C0FBE29272E99F00",
      "latest_block_height": "9718",
      "latest_block_time": "2022-11-03T01:41:59.320785278Z",
      "catching_up": false
    },
    "validator_info": {
      "address": "0F46542A32FAC85D75312A43C3D64C5E0B7519A5",
      "pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "BIZF+OhMN79nmJKRFB9tX3rCrLKlCMKqWu+arvi1Sw7gc5eneQHxx5i7wkvSmcXU78YgCBZNUX/a54vBiT7ovxo="
      },
      "voting_power": "1"
    }
  }
}
```
Through the [bttc test network block browser](https://testnet.bttcscan.com/), the current latest height is 14035391, but the synchronization status of Delivery is catching_ Up is false,
```
"latest_block_height": "9718",
"latest_block_time": "2022-11-03T01:41:59.320785278Z",
"catching_up": false
```
Is this information correct?

**Comment by bladehan1** [comment]
Please check your delivery genesis.json.
 
The command will get the delivery status instead of the bttc status

```
curl localhost:26657/status  
```
