### ISSUE TITLE
Error when running bttc-cli setup devnet

### ISSUE THREAD

**Issue by Leonardo-Henrique** [bttcprotocol/bttc#4]
#### System information

Geth version: `geth version`
OS & Version: Debian GNU/Linux 10 
Commit hash : (if `develop`)

#### Expected behaviour

The node directory be generated

#### Actual behaviour

It fails in "Generate genesis.json" step 

#### Steps to reproduce the behaviour

Dependencies installed:
Git v2.30.1
g++ 8.3.0
Go 1.16.12
Nodejs v11.0.0
Rabbitmq-server started 
Solc v0.8.10

git clone https://github.com/bttcprotocol/delivery.git
cd delivery
make install

git clone https://github.com/bttcprotocol/bttc
cd bttc
make bttc

npm install -g @bttcnetwork/bttc-cli

bttc-cli setup devnet

(fill the fields)

#### Backtrace

````
✖ Generate genesis.json
      → Bttc validator set file updated.
    Setup Bttc keystore and genesis files
    Remote
(node:28355) UnhandledPromiseRejectionWarning: Error: Command failed: node generate-genesis.js --bttc-chain-id 1029 --delivery-chain-id delivery-1029
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn solc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)

Bttc validator set file updated.

    at makeError (/home/leonardo/.nvm/versions/node/v11.0.0/lib/node_modules/@bttcnetwork/bttc-cli/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/leonardo/.nvm/versions/node/v11.0.0/lib/node_modules/@bttcnetwork/bttc-cli/node_modules/execa/index.js:278:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:28355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28355) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

````

When submitting logs: please submit them as text and not screenshots.

**Comment by xq-lu** [comment]
hi,Leonardo

it seems like the error occurs when solc compiles contracts, I would suggest using solc version v0.5.x instead of solc v0.8.10.
the lastest solc version may not be compatible with the contracts which the bttc project use.

more details about the deployment ,please check https://doc.bittorrentchain.io/v1/doc/node.html#deploy-node .

**Comment by Leonardo-Henrique** [comment]
I uninstalled version 0.8 and subsequently installed versions 0.5.11 and 0.5.17. In both, the same error occurred. 

```
solcjs --version
0.5.11+commit.c082d0b4.Emscripten.clang
```

**Comment by xq-lu** [comment]
> 

hi,leonardo.
i found you install solcjs .i guess you use 'npm install -g solc' to install solcjs,however,solcjs is different from solc.from [this page](https://docs.soliditylang.org/en/v0.5.17/installing-solidity.html),it said 'The comandline options of solcjs are not compatible with solc and tools (such as geth) expecting the behaviour of solc will not work with solcjs.' 

i suggest install solc instead of solcjs.
if solc installed correctly,it will show `solc --version
solc, the solidity compiler commandline interface
Version: 0.5.17+commit.d19bba13.Darwin.appleclang`

**Comment by xq-lu** [comment]
> > 
> 
> hi,leonardo. i found you install solcjs .i guess you use 'npm install -g solc' to install solcjs,however,solcjs is different from solc.from [this page](https://docs.soliditylang.org/en/v0.5.17/installing-solidity.html),it said 'The comandline options of solcjs are not compatible with solc and tools (such as geth) expecting the behaviour of solc will not work with solcjs.'
> 
> i suggest install solc instead of solcjs. if solc installed correctly,it will show `solc --version solc, the solidity compiler commandline interface Version: 0.5.17+commit.d19bba13.Darwin.appleclang`

by the way,if you use mac,you can use brew to install socl,if you use linux,snap is a easy way to install solc.

**Comment by Leonardo-Henrique** [comment]
I have uninstalled the solc that I got via NPM (solcjs) and installed solc via snap, but I can't run any solc commands even though the installation completes successfully. I'm trying to understand why.

**Comment by Leonardo-Henrique** [comment]
Update: I solved this problem with `export PATH=$PATH:/snap/bin`, right now I got another error (omG haha) in the final steps, when I run `sh bttc-setup.sh` this is the ouput:

bttc-setup.sh: 12: bttc-setup.sh: bttc: not found
cp: cannot stat '/workspace/bttc/devnet/node0/bttc/nodekey': No such file or directory
cp: cannot stat '/workspace/bttc/devnet/node0/bttc/static-nodes.json': No such file or directory
Setup done!%

I checked and both nodekey and static-nodes.json are in the folder. I replaced all the files indicated and corrected the node dir in the sh files for /workspace/bttc/devnet/node0/

**Comment by xq-lu** [comment]
> devnet

it seems like 'bttc command' didn't install correctly. could you type 'which bttc' to check if bttc command is installed in the right place? 

if it shows `' xxxxx@xxxxxMacBook-Pro ~ % which bttc
bttc not found'` ,it means bttc command is not installed.

if it shows `'[xxxx@xxxxxx ~]$  which bttc
~/bin/bttc'` which means you have installed the bttc command correctly.

**Comment by Leonardo-Henrique** [comment]
I tried but nothing happens, I decided restart from scratch, and now, when I run `nohup sh delivery-start.sh>>logs/deliveryd.log 2>&1 &` I got it in logs:

```
nohup: ignoring input
+ NODE_DIR=/home/leonardo/workspace/node/bttc/devnet/node0
+ DELIVERY_HOME_DIR=/home/leonardo/workspace/node/bttc/devnet/node0/deliveryd
+ deliveryd --home /home/leonardo/workspace/node/bttc/devnet/node0/deliveryd start
delivery-start.sh: 8: delivery-start.sh: deliveryd: not found
```

looking to delivery-start.sh I saw delivery command in one of lines and I replaced with the absolute path until the delivery dir so I got 

```
+ NODE_DIR=/home/leonardo/workspace/node/bttc/devnet/node0
+ DELIVERY_HOME_DIR=/home/leonardo/workspace/node/bttc/devnet/node0/deliveryd
+ /home/leonardo/workspace/node/bttc/devnet/node0/deliveryd --home /home/leonardo/workspace/node/bttc/devnet/node0/deliveryd start
delivery-start.sh: 8: delivery-start.sh: /home/leonardo/workspace/node/bttc/devnet/node0/deliveryd: Permission denied
```

both delivery-start.sh and deliveryd are with all permissions given

**Comment by xq-lu** [comment]
> I tried but nothing happens, I decided restart from scratch, and now, when I run `nohup sh delivery-start.sh>>logs/deliveryd.log 2>&1 &` I got it in logs:
> 
> ```
> nohup: ignoring input
> + NODE_DIR=/home/leonardo/workspace/node/bttc/devnet/node0
> + DELIVERY_HOME_DIR=/home/leonardo/workspace/node/bttc/devnet/node0/deliveryd
> + deliveryd --home /home/leonardo/workspace/node/bttc/devnet/node0/deliveryd start
> delivery-start.sh: 8: delivery-start.sh: deliveryd: not found
> ```
> 
> looking to delivery-start.sh I saw delivery command in one of lines and I replaced with the absolute path until the delivery dir so I got
> 
> ```
> + NODE_DIR=/home/leonardo/workspace/node/bttc/devnet/node0
> + DELIVERY_HOME_DIR=/home/leonardo/workspace/node/bttc/devnet/node0/deliveryd
> + /home/leonardo/workspace/node/bttc/devnet/node0/deliveryd --home /home/leonardo/workspace/node/bttc/devnet/node0/deliveryd start
> delivery-start.sh: 8: delivery-start.sh: /home/leonardo/workspace/node/bttc/devnet/node0/deliveryd: Permission denied
> ```
> 
> both delivery-start.sh and deliveryd are with all permissions given

from your error msg just paste. seems like you didn't install delivery correctly.
I will suggest. you use the same system account(eg: root) to set up the cli and install the delivery from the sourcecode.
