### ISSUE TITLE
Error when install bttc-cli

### ISSUE THREAD

**Issue by daniel-tron** [bttcprotocol/bttc#8]
Can't install if doesn't setup a GitHub account with ssh key, i do have GitHub account, but doesn't make sense copy my private key to the server which deploy BTTC node.

**Ubuntu 20.04**
npm install -g @bttcnetwork/bttc-cli
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.0
npm notice Run npm install -g npm@8.3.0 to update!
npm notice 
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote **ssh://git@github.com/atvanguard/moonwalker.git**
npm ERR! Warning: Permanently added 'github.com,140.82.112.3' (ECDSA) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: **Could not read from remote repository.**
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-08T09_50_31_873Z-debug.log

**Comment by xq-lu** [comment]
> Can't install if doesn't setup a GitHub account with ssh key, i do have GitHub account, but doesn't make sense copy my private key to the server which deploy BTTC node.
> 
> **Ubuntu 20.04** npm install -g @bttcnetwork/bttc-cli npm notice npm notice New minor version of npm available! 8.1.2 -> 8.3.0 npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.0 npm notice Run npm install -g npm@8.3.0 to update! npm notice npm ERR! code 128 npm ERR! An unknown git error occurred npm ERR! command git --no-replace-objects ls-remote **ssh://git@github.com/atvanguard/moonwalker.git** npm ERR! Warning: Permanently added 'github.com,140.82.112.3' (ECDSA) to the list of known hosts. npm ERR! [git@github.com](mailto:git@github.com): Permission denied (publickey). npm ERR! fatal: **Could not read from remote repository.** npm ERR! npm ERR! Please make sure you have the correct access rights npm ERR! and the repository exists.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2022-01-08T09_50_31_873Z-debug.log

seems like the error return when git pull repo 'moonwalker'.but as i known, these repo were public,i did not repeat the error you just paste.
so i guess if you can check the privilege settings

**Comment by daniel-tron** [comment]
https://github.com/npm/git/pull/7
https://github.com/npm/git/issues/31
